steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
- id: 'ls dir'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      cd 01_SimpleApp/app
      pwd
      ls
      cat Dockerfile
- id: 'docker build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/iwasnothing-herhack-team3/location-image', '01_SimpleApp/app']
